apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum-frontend-config
  namespace: dev
data:
  config.json: |
    {
    "authPublicUrl":"https://example.com/auth/",
    "appFrontendUrl":"https://example.com/app",
    "appBackendApiUrl":"https://example.com/api/",
    "ethereumBackendApiUrl":"https://example.com/ethereum-backend"
    }